Vagrant.configure("2") do |config|
  ["bookworm64", "testing64"].each do |version|
    config.vm.define "satfs-debian-#{version}" do |test_vm|
      test_vm.vm.box = "debian/#{version}"
      test_vm.vm.hostname = "satfs-debian-#{version}"
      test_vm.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end

      test_vm.vm.synced_folder "../..", "/vagrant", mount_options: ["ro"]

      test_vm.vm.provision "shell", inline: <<-SHELL
        echo 'libc6:amd64 libraries/restart-without-asking boolean true' | debconf-set-selections
        apt-get update
        apt-get install -y fuse vim psmisc rsync strace ltrace attr python3-pytest python3-pytest-forked python3-psutil
        # packages for satfs
        apt-get install -y python3 python3-pip python-is-python3 python3-fuse python3-prctl python3-yaml python3-systemd
        mkdir /mnt/satfs && chown vagrant:vagrant /mnt/satfs
      SHELL
    end
  end
end
