Vagrant.configure("2") do |config|
  [
    { name: "satfs-debian-bookworm", image: "debian/bookworm64" },
    { name: "satfs-debian-trixie", image: "debian/testing64" }
  ].each do |vm|
    config.vm.define vm[:name] do |test_vm|
      test_vm.vm.box = vm[:image]
      test_vm.vm.hostname = vm[:name]
      test_vm.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end

      test_vm.vm.synced_folder "../..", "/vagrant", mount_options: ["ro"]

      test_vm.vm.provision "shell", inline: <<-SHELL
        echo 'libc6:amd64 libraries/restart-without-asking boolean true' | debconf-set-selections
        apt-get update
        apt-get install -y fuse vim psmisc rsync strace ltrace attr python3-pytest python3-pytest-forked python3-psutil
        # packages for satfs
        apt-get install -y python3 python3-pip python-is-python3 python3-fuse python3-prctl python3-yaml python3-systemd

        sed 's/^#user_allow_other/user_allow_other/' -i /etc/fuse.conf
        groupadd --system satfs
        useradd --system --gid satfs --shell /usr/sbin/nologin satfs
        mkdir /mnt/satfs && chown vagrant:vagrant /mnt/satfs
      SHELL
    end
  end
end
