Vagrant.configure("2") do |config|
  config.vm.define "vagrant-satfs" do |test_vm|
    test_vm.vm.box = "debian/testing64"
    test_vm.vm.hostname = "vagrant-satfs"
    test_vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.synced_folder "../..", "/vagrant", mount_options: ["ro"]

  config.vm.provision "shell", inline: <<-SHELL
    echo 'libc6:amd64 libraries/restart-without-asking boolean true' | debconf-set-selections
    apt-get update
    apt-get install -y fuse vim psmisc rsync strace ltrace attr python3-pytest python3-pytest-forked python3-psutil
    # packages for satfs
    apt-get install -y python3 python3-pip python-is-python3 python3-fuse python3-prctl python3-yaml python3-systemd
    mkdir /mnt/satfs && chown vagrant:vagrant /mnt/satfs
  SHELL
end
